name: CI Diagnostic

on:
  push:
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest

    steps:
      - name: Check runner
        run: |
          echo "Runner is working"
          whoami
          pwd